// -----------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs" company="David Wright">
// Copyright (c) David Wright. All rights reserved.
// </copyright>
// -----------------------------------------------------------------------

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis should be spaced correctly", Justification = "Wanted to get lambda on a single line.", Scope = "member", Target = "~M:AOC2021.Day01.Result1~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis should be spaced correctly", Justification = "Wanted to get lambda on a single line.", Scope = "member", Target = "~M:AOC2021.Day01.Result2~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.SpacingRules", "SA1009:Closing parenthesis should be spaced correctly", Justification = "Wanted to get lambda on a single line.", Scope = "member", Target = "~M:AOC2021.Day01.Result2Variant~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1111:Closing parenthesis should be on line of last parameter", Justification = "Wanted to get lambda on a single line.", Scope = "member", Target = "~M:AOC2021.Day01.Result1~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1111:Closing parenthesis should be on line of last parameter", Justification = "Wanted to get lambda on a single line.", Scope = "member", Target = "~M:AOC2021.Day01.Result2~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1111:Closing parenthesis should be on line of last parameter", Justification = "Wanted to get lambda on a single line.", Scope = "member", Target = "~M:AOC2021.Day01.Result2Variant~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.ReadabilityRules", "SA1106:Code should not contain empty statements", Justification = "I tried doing it differently. It was less clear and broke something.", Scope = "member", Target = "~M:AOC2021.Day04.PrepData~System.ValueTuple{System.Int32[],AOC2021.Bingo.BingoBoard[]}")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Not going to document every Day class. They are all the same.", Scope = "member", Target = "~M:AOC2021.Day04.Result2~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Not going to document every Day class. They are all the same.", Scope = "type", Target = "~T:AOC2021.IDay")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Not going to document every Day class. They are all the same.", Scope = "member", Target = "~M:AOC2021.Data.DataStore.#ctor")]
[assembly: SuppressMessage("Style", "IDE0042:Deconstruct variable declaration", Justification = "Clearer in this case, with named tuple, imo.", Scope = "member", Target = "~M:AOC2021.Day02.Result1~System.Int32")]
[assembly: SuppressMessage("Style", "IDE0042:Deconstruct variable declaration", Justification = "Clearer in this case, with named tuple, imo.", Scope = "member", Target = "~M:AOC2021.Day02.Result2~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Not going to document every Day class. They are all the same.", Scope = "member", Target = "~M:AOC2021.Day05.Result1~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Not going to document every Day class. They are all the same.", Scope = "member", Target = "~M:AOC2021.Day05.Result2~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Not going to document every Day class. They are all the same.", Scope = "member", Target = "~M:AOC2021.Day02.#ctor(AOC2021.Data.DataStore)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Just not gonna document every public or internal. Bite me.", Scope = "member", Target = "~M:AOC2021.Day02.Result1~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Just not gonna document every public or internal. Bite me.", Scope = "member", Target = "~M:AOC2021.Day02.Result2~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Just not gonna document every public or internal. Bite me.", Scope = "member", Target = "~M:AOC2021.Day03.#ctor(AOC2021.Data.DataStore)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Just not gonna document every public or internal. Bite me.", Scope = "member", Target = "~M:AOC2021.Day03.Result1~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Just not gonna document every public or internal. Bite me.", Scope = "member", Target = "~M:AOC2021.Day03.Result2~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Just not gonna document every public or internal. Bite me.", Scope = "member", Target = "~M:AOC2021.Day04.#ctor(AOC2021.Data.DataStore)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Just not gonna document every public or internal. Bite me.", Scope = "member", Target = "~M:AOC2021.Day04.Result1~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Just not gonna document every public or internal. Bite me.", Scope = "member", Target = "~M:AOC2021.Day05.#ctor(AOC2021.Data.DataStore)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Just not gonna document every public or internal. Bite me.", Scope = "member", Target = "~M:AOC2021.Day01.#ctor(AOC2021.Data.DataStore)")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Just not gonna document every public or internal. Bite me.", Scope = "member", Target = "~M:AOC2021.Day01.Result1~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Just not gonna document every public or internal. Bite me.", Scope = "member", Target = "~M:AOC2021.Day01.Result2~System.Int32")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Just not gonna document every public or internal. Bite me.", Scope = "member", Target = "~P:AOC2021.Map.Map.MapPoint.HitCount")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Just not gonna document every public or internal. Bite me.", Scope = "member", Target = "~P:AOC2021.Map.Map.MapPoint.P")]
[assembly: SuppressMessage("StyleCop.CSharp.DocumentationRules", "SA1600:Elements should be documented", Justification = "Just not gonna document every public or internal. Bite me.", Scope = "member", Target = "~M:AOC2021.Map.Map.MapPoint.#ctor(System.Drawing.Point,System.Int32)")]
